project:
  type: book  
  output-dir: docs

profiles:
  windows:
    post-render: compile-slides.bat

book:
  title: "Workplace Injury Risk: Office Workers vs. Manufacturing Workers"
  author: "Brynn"
  date: today
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-data.qmd
    - 03-methods.qmd
    - 04-results.qmd
    - 05-conclusion.qmd
    - references.qmd
    

bibliography: references1.bib
 
crossref:
  fig-title: "Figure"
  tbl-title: "Table"
 
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    documentclass: scrreprt
    number-sections: true
